### ISSUE TITLE
Precedence of comparing operations

### ISSUE THREAD

**Issue by Prometheus3375** [lep/pjass#10]
```
function foo takes nothing returns nothing
    local boolean b = 5 > 4 == 5 < 7
endfunction
```
This code produces error:
![image](https://github.com/lep/pjass/assets/35541026/502b81ba-40af-4cdb-bd81-5651df86f901)

Actually, at first `<` and `>` are evaluated and then `==`.

---

```
function foo takes nothing returns nothing
    local boolean a = 1 != 2 != false
endfunction
```
Error:
![image](https://github.com/lep/pjass/assets/35541026/a6c858a5-d69c-4a0b-8025-f67e5f01436d)

This once correctly evaluates to `true`.

There can be other issues related to precedence in comparisons.

**Comment by lep** [comment]
Surprising. I *think* i checked this once (long ago). So either i failed or they actually touched the parsing part in recent patches. Thanks for the report. Should be fixed with dec9c9c523f4793746557d92f6ab9429ffa2ff21

**Comment by Prometheus3375** [comment]
I've just checked in 1.26, map was working OK.

According to the description I found, precedence goes in the following way (from highest to lowest):

- Parenthesis.
- Negation (unary minus) and `not`.
- Multiplication, division, modulo.
- Addition and subtraction.
- >, >=, <, <=.
- == and !=.
- `and`. If its 1st operand evaluates to `false`, 2nd operand is not evaluated at all.
- `or`. If its 1st operand evaluates to `true`, 2nd operand is not evaluated at all.


I am not sure about comparison operations and modulo.

**Comment by Prometheus3375** [comment]
Well, actually...

```
if false and true or true then
    call BJDebugMsg("true")
else 
    call BJDebugMsg("false")
endif
```

In this case the whole expression is evaluated to `false`. 🤣
This is either because of `and` optimization, `or` is never evaluated.
